# Generated by Django 4.1.12 on 2024-02-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aluno_numero_turma_alter_turma_numero_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='ID_Escola',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
