# Generated by Django 4.1.12 on 2024-03-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sala_id_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='Dia_semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='ID_Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
