# Generated by Django 4.1.12 on 2024-03-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_horario_dia_semana_alter_sala_id_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('ID_Utilizador', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nome_Utilizador', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('ID_Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professor')),
            ],
        ),
    ]
