# Generated by Django 4.1.12 on 2024-03-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_admin_escola_id_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ID_Escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
        migrations.AlterField(
            model_name='admin_escola',
            name='ID_Escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
            preserve_default=False,
        ),
    ]
