# Generated by Django 4.1.12 on 2024-03-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_curso_id_escola_alter_admin_escola_id_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ID_Escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
        ),
    ]
