# Generated by Django 4.1.12 on 2024-04-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_professor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_horario',
            fields=[
                ('ID_Tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fim', models.TimeField()),
                ('Formato_Horas', models.CharField(max_length=200)),
                ('ID_Escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.escola')),
            ],
        ),
    ]
