# Generated by Django 4.1.12 on 2024-04-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_tipo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ID_Escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.escola'),
            preserve_default=False,
        ),
    ]
